// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNJK4JgAHuGgxVEdIZ2q2ebI8Rh2WZO-c',
    appId: '1:812120767687:web:77d199f74047fdf72352e2',
    messagingSenderId: '812120767687',
    projectId: 'grabberapp-9e1a1',
    authDomain: 'grabberapp-9e1a1.firebaseapp.com',
    databaseURL: 'https://grabberapp-9e1a1-default-rtdb.firebaseio.com',
    storageBucket: 'grabberapp-9e1a1.appspot.com',
    measurementId: 'G-QQQ70B9KHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB41_B_IGfinPqhHJBmPhZDBUVq_MEKfEU',
    appId: '1:812120767687:android:e30132344b1a56872352e2',
    messagingSenderId: '812120767687',
    projectId: 'grabberapp-9e1a1',
    databaseURL: 'https://grabberapp-9e1a1-default-rtdb.firebaseio.com',
    storageBucket: 'grabberapp-9e1a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNCiaDCWnh3FLPWOGO1loETygkIBe5EU',
    appId: '1:812120767687:ios:58525f5247f2002e2352e2',
    messagingSenderId: '812120767687',
    projectId: 'grabberapp-9e1a1',
    databaseURL: 'https://grabberapp-9e1a1-default-rtdb.firebaseio.com',
    storageBucket: 'grabberapp-9e1a1.appspot.com',
    iosBundleId: 'com.example.usersApp',
  );
}
